### ISSUE TITLE
议题：流水线的定义与组织方式

### ISSUE THREAD

**Issue by gagraler** [go-arcade/arcade#1]
# 流水线的定义与组织方式

通常来说，一条CI/CD的流水线主要是为了完成打包、测试、代码分析与部署等功能。要有效定义流水线的方式，需要我们事先明确讨论和规划。

### Github Actions  - 基于结构型代码（YML）定义方式的分析

我们先看看基于 YML 定义方式的 Github Actions：它是通过项目 `.github/workflows` 目录下的 yml 定义，这是一种编程式的风格。类似于 Github 上选择 Markdown 而不是 Word 文档一样，虽然更贴合极客风格，但操作略显繁琐。

在 Github Actions 中，当流水线需要从一个 job 传输数据至另一个 job 时，它强制要求你通过 needs 来完成 jobs 的关联，同时也让流水线之间的关系定义**不够直观**：

```yml
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.step1.outputs.result }}  # 将 step 的输出保存为 job 的 output
    steps:
      - id: step1
        run: echo "::set-output name=result::Hello from job1"  # 设置输出
    
  job2:
    needs: job1  # 表示 job2 依赖 job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job1 result: ${{ needs.job1.outputs.result }}"  # 获取 job1 的输出
```

当涉及到构建产物等文件的传递时还需要通过外部的 actions 如 `actions/upload-artifac` 与 `actions/download-artifact` 来实现，这显然并不是很符合更加直观 `INPUT/OUTPUT`  的计算机第一性原理。

#### GitHub Actions UI 界面的问题

GitHub Actions 的 UI 界面展示了流水线中 jobs 之间的组织关系，然而，仅通过查看 YML 文件，难以直观理解这些关系，并且界面不会详细展示每个 job 的 steps 结构，无法直接进行编辑：

![image](https://github.com/user-attachments/assets/bd7f817f-64fb-4b38-9076-5b69ff42d258)

### Jenkins - 基于 Pipeline Script 定义方式的分析

Jenkins 虽然历史悠久且功能强大，但其较为落后的组织形式和复杂的 `Pipeline` 定义，在现代 CI/CD 工具中显得略为笨重与繁琐。

Jenkins 的 Pipeline 主要通过 Jenkinsfile 进行定义，它采用 `Groovy` 语言编写并且提供了包括 `Declarative` 和 `Scripted Pipeline` 的定义方式，但这两种方式都要求使用者具备一定的编程基础且了解。一个典型的 Declarative Pipeline 示例如下：

```groovy
pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}
```

stages 类似 Github Actions 的 jobs，尽管定义上很灵活，但 Jenkins 的 Pipeline 同样没有直观的输入输出流概念。如果需要在多个 stages 之间传递数据通常需要手动设置环境变量或借助 stash 和 unstash 来保存和传递构建产物，这让定义过程变得繁琐且易出错。

#### Jenkins 落后的 UI 与组织形式

Jenkins 虽然提供了基于节点和任务的视图来管理构建过程，但整体 UI 界面显得陈旧、复杂，尤其是当涉及到多节点、多任务管理时，用户难以通过直观的界面进行调度和编排：

![image](https://github.com/user-attachments/assets/4a962ba9-5962-47f4-9de1-a7a45bd149d3)

### 云效 - 基于可视化编排工作台定义方式的分析

云效作为一款面向 DevOps 的平台工具，采用了可视化编排工作台的方式定义 CI/CD 流水线。相比其他，云效的可视化编排在操作简便性和输入输出的直观性上具有明显优势。

它支持拖拽式编辑工作流并提供了更加即时的执行状态展示，让用户能够在工作流执行的同时看到各个步骤的输入、输出情况，可以及时进行调整并重新运行，优化了流水线的迭代速度。

![image](https://github.com/user-attachments/assets/6e59d559-58bb-426f-9277-48f784dbe98f)

通过可视化编排工作台，可以将**复杂的流水线定义简化为可拖拽的模块和直观的输入输出流设计**。使得 CI/CD 流水线不仅对开发者友好，也对其他非开发部门的协作变得更加容易。它在操作简便性、可视化体验和输入输出的直观性方面有着显著的优势，也是我们对于现代的 CI/CD 工具流水行定义的一个重要指向。

那么接下来我们将展开可视化编排工作台定义方式的数据组织形式的拆解与定义，后续将在此 issue 下补充相关定义。
